namespace GameResourceConfig {
    export const Domain: string = "http://m.17guess.cn/1/";
    export const LoadResourcesConfig: Array<any> = [
        { url: "res/atlas/ui.atlas", type: Laya.Loader.ATLAS },
        { url: "res/atlas/ui/vertical.atlas", type: Laya.Loader.ATLAS },
        { url: "res/atlas/ui/poker.atlas", type: Laya.Loader.ATLAS },
        { url: "ui/bg_header.png", type: Laya.Loader.IMAGE },
        { url: "ui/bg.png", type: Laya.Loader.IMAGE },
        { url: "ui/mask.png", type: Laya.Loader.IMAGE },
        { url: "ui/bg_alert.png", type: Laya.Loader.IMAGE },
        { url: "ui/bg_record.png", type: Laya.Loader.IMAGE },
        { url: "ui/recordLine.png", type: Laya.Loader.IMAGE },
        { url: "ui/tip.png", type: Laya.Loader.IMAGE },
        { url: "ui/bg_round.png", type: Laya.Loader.IMAGE },
        { url: "ui/bg_histrory.png", type: Laya.Loader.IMAGE },
        { url: "ui/bg_bet.png", type: Laya.Loader.IMAGE },
        { url: "ui/bg_door.png", type: Laya.Loader.IMAGE },
        { url: "ui/bg_chips.png", type: Laya.Loader.IMAGE },
        { url: "ui/bg_bet_more.png", type: Laya.Loader.IMAGE },
        { url: "ui/bg_bet_more_v.png", type: Laya.Loader.IMAGE },
        { url: "ui/vertical/bg_alert_v.png", type: Laya.Loader.IMAGE },
        { url: "ui/vertical/bet_v1.png", type: Laya.Loader.IMAGE },
        { url: "ui/vertical/betBg_v.png", type: Laya.Loader.IMAGE },
        { url: "ui/vertical/bg_bet_v.png", type: Laya.Loader.IMAGE },
        { url: "ui/vertical/bg_chips_v.png", type: Laya.Loader.IMAGE },
        { url: "ui/vertical/bg_door_v.png", type: Laya.Loader.IMAGE },
        { url: "ui/vertical/bg_header_v.png", type: Laya.Loader.IMAGE },
        { url: "ui/vertical/bg_record_v.png", type: Laya.Loader.IMAGE },
        { url: "ui/vertical/bg_round_v.png", type: Laya.Loader.IMAGE },
        { url: "ui/vertical/bg_v.png", type: Laya.Loader.IMAGE },
        { url: "ui/vertical/tip_v.png", type: Laya.Loader.IMAGE },
    ]
}